In [1]:
import sys
sys.path.append("../src")

from generate_data import generate_users

In [2]:
import pandas as pd
import numpy as np

from db_connection import get_engine
engine = get_engine()

In [3]:
df = generate_users(3000)
display(df.head())
display(df.info())

  acquisition_channel   plan  country signup_date
0             organic  basic   Russia  2026-08-30
1         paid_search  basic    China  2026-09-18
2             organic  basic    China  2026-04-16
3             organic    pro  Belarus  2025-11-07
4             organic   free    China  2026-06-10

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   acquisition_channel  3000 non-null   str
 1   plan                 3000 non-null   str
 2   country              3000 non-null   str
 3   signup_date          3000 non-null   object
dtypes: object(1), str(3)
memory usage: 93.9+ KB

None

Столбец "id" не создался, поэтому записываем датафрейм в sql таблицу

In [5]:
df.to_sql("users", engine, if_exists="append", index=False)

1000

In [6]:
pd.read_sql("SELECT COUNT(*) FROM users;", engine)

   count
0   3000

In [8]:
users_db = pd.read_sql("SELECT * FROM users;", engine)
users_db

        id acquisition_channel   plan  country signup_date
0        1             organic  basic   Russia  2026-08-30
1        2         paid_search  basic    China  2026-09-18
2        3             organic  basic    China  2026-04-16
3        4             organic    pro  Belarus  2025-11-07
4        5             organic   free    China  2026-06-10
...    ...                 ...    ...      ...         ...
2995  2996             organic   free    China  2026-03-18
2996  2997             organic    pro   Russia  2026-01-29
2997  2998             organic   free  Belarus  2025-06-06
2998  2999         paid_search  basic    China  2026-06-18
2999  3000            referral  basic  Belarus  2025-09-24

[3000 rows x 5 columns]